Potential Code Refactor
ankingcodes/codemon pull request #65
Opened 2020-12-08 19:46 UTC by tusharnankani

2020-12-08 19:49 UTC, tusharnankani commented
The code could be refactored more, but I did not know if they would be required later. There were a few unused imported modules and variables.

2020-12-09 06:03 UTC, ankingcodes commented
@tusharnankani - Thanks for making the PR. Can you please resolve the conflicts ?

2020-12-09 10:43 UTC, tusharnankani commented
Fixed 👍🏼

2020-12-09 12:52 UTC, ankingcodes requested changes

2020-12-09 12:52 UTC, ankingcodes commented on .deepsource.toml
> +  runtime_version = "3.x.x"
@tusharnankani - Did you setup deep source for this project ?

2020-12-09 12:56 UTC, ankingcodes commented
@tusharnankani - on reviewing your PR, I found that that only two lines of code were altered, for which it is difficult for me to give you points. There are many more areas in the codebase which require refactoring. You may go ahead and do some more. For example, using the function declared in `CodemonParse.py` inside of  `codemon.py` since they are related and many more. 

Let me know if you're interested to do some work, else we may either merge this one but you won't get much points for NWoC ?

2020-12-09 12:57 UTC, tusharnankani commented
> The code could be refactored more, but I did not know if they would be required later. There were a few unused imported modules and variables.

I mentioned this earlier.

2020-12-29 14:24 UTC, tusharnankani commented
> > The code could be refactored more, but I did not know if they would be required later. There were a few unused imported modules and variables.
> 
> I mentioned this earlier^ So let me know, I could optimize the code more.


HI @ankingcodes 
Any updates?

2021-01-03 06:57 UTC, tusharnankani commented
> > > The code could be refactored more, but I did not know if they would be required later. There were a few unused imported modules and variables.
> > 
> > 
> > I mentioned this earlier^ So let me know, I could optimize the code more.
> 
> HI @ankingcodes
> Any updates?

@ankingcodes you can merge it under nwoc and kwoc 👍🏻

2021-08-01 01:01 UTC, closed without merging