fetch-improvements
ankingcodes/codemon pull request #72
Opened 2020-12-11 20:54 UTC by Enigmage

Closes #66 

#### Required Changes

- Removes `codemon fetch <contest_name>` command as that is redundant to the functionality of codemon, especially after the addition of  `-f /--fetch` flag. Also added error checks so that `codemon fetch` is entered as a single command.
-  Every sample test case string after scraping from codeforces  begins with a  `\n` character. So to solve the problem of an extra newline at the beginning of inputs and outputs, all that was to be done was to write the `i` and `o` strings to input and output files from the 1st index instead of the 0th. Example.
```py
f.write(i[1:])
```
- As suggested changed the coloring of all verbose messages to white, except error messages which will be red.

#### Additional Changes

There were a few inconsistencies in the functionality of codemon and `CodemonFetch` module that I've fixed.

- It was the intended behaviour that the user can enter any string as the contest name as long  it contained the correct contest number in it for example `contest_1455` or `round_1455`. Currently if the user enters this as the contest name during init they will get the correct filenames for round 1455 but if they were to run `codemon fetch`  inside this directory instead of the sample test cases being written down into their correct place, an extra folder would be created with the contest number as its name, that contained only the inputs and outputs. This is because unlike `get_filename` function in CodemonMeta.py, `fetch_tests` function did not clearly differentiate between the contest number and contest name while scraping. This created the issue. So with this update I've ensured that clear distinction is made between the contest number and contest name. So the user can name their contest directory like `round_1455` etc without facing any issue.

- Since init now takes care of making the proper directory structure the `make_structure` function in `CodemonFetch` module was redundant. So I changed it to `check_structure` which only checks for the presence of correct directory structure while scraping, if the correct structure is not present it will generate an error. Which should be the correct behaviour. So if the user now accidentally runs `codemon fetch` in some other random directory that happened to have a valid codeforces contest number in its name, codemon fetch will now error out instead of creating a question folder with inputs and outputs and crowding up the users directory. This can also act as a very good error check as to whether the user is running `codemon fetch` from inside contest directory or not.

- Added better error checks to `fetch_tests` function, so if fetching of sample test cases fails user will know exactly why.
- There were few unused imports, redundant variables and code that I've removed to make the code more concise.

2020-12-14 07:24 UTC, ankingcodes commented
@Enigmage - Sorry for delay in review. Could you also work on improving the documentation (how to use commands, naming system for directory, a GIF demonstrating codemon, etc) on our README and make a new PR for that too ?

2020-12-14 11:57 UTC, Enigmage commented
@ankingcodes Yeah sure I can work on that. Can you just give me a rough idea of what all you'd want to be included in the README and the Gif so that I can start working accordingly ?

2020-12-14 12:09 UTC, ankingcodes commented
Take each of the commands for example and desribe each of them in detail. For example, for `codemon init -f round_1342`, you can explain what the command does, how many ways the command can be written, for example it can be written as `codemon init --fetch 1342 ` also. Then you can go on desribing the proper directory nomenclature etc. 

I'd be much happy if you can generate docs from the code itself, maybe using something like [pydocs](https://docs.python.org/3/library/pydoc.html). Do it whichever way suits you better.

2020-12-15 11:39 UTC, Enigmage commented
@ankingcodes Hey I forgot to ask, are you expecting the documentation changes in this PR itself ? Because I was was hoping you could review and if its all fine merge this PR first since it has some important fixes for `codemon fetch`. And then I will be making a PR for adding documentation separately (already working on it on a different branch). Is this okay?

2020-12-20 04:03 UTC, ankingcodes requested changes

2020-12-20 04:03 UTC, ankushbhardwxj commented on codemon/CodemonInit.py
> +    print('Directories are made.')
Can we have only one output "Created directory {contestName}" for creation of directories ? And "Failed to create directory {contestName} !" ?

2020-12-20 04:03 UTC, ankushbhardwxj commented on codemon/CodemonInit.py
>    print("Making single file")
Please get rid of this line.

2020-12-20 04:03 UTC, ankushbhardwxj commented on codemon/CodemonInit.py
> +  print(f"Created {filename}.{ext}")
Rewrite this as : `Created file {filename}.{ext}`

2020-12-20 04:03 UTC, ankushbhardwxj commented on codemon/CodemonHelp.py
> +  print("codemon fetch  - - - - - - - - - - - fetch all sample test cases for the current contest directory")
Please rewrite this as : `fetches testcases from CodeForces`.

2020-12-20 04:03 UTC, ankingcodes commented on codemon/CodemonFetch.py
> +          flag = False
change the flag variable to some proper name, for example, `correctDirStruct` ?

2020-12-20 04:03 UTC, ankingcodes commented
@Enigmage - few minor changes required here.

2020-12-20 11:23 UTC, Enigmage commented on codemon/CodemonInit.py
> +    print('Directories are made.')
You are right, it is cleaner this way.

2020-12-20 11:26 UTC, Enigmage commented
@ankingcodes made the requested changes. Also added info about the `-f` flag for fetch in the Help section which was missing, see if you like it. Couldn't include `--fetch` as the message was getting long.

2020-12-21 09:25 UTC, ankingcodes approved these changes
Looks good ! Thanks @Enigmage

2020-12-21 09:25 UTC, merged