updated codemon --help
ankingcodes/codemon pull request #78
Opened 2020-12-16 10:29 UTC by lucifer0987

closes #67 
added short and concise help messages.

2020-12-20 04:38 UTC, ankingcodes requested changes

2020-12-20 04:38 UTC, ankingcodes commented on codemon/CodemonHelp.py
> +  print("codemon fetch <contestName> - - - - - -  Fetches sample TC from CF for <contestName> round")
TC from CF is not proper. It can be difficult for people to know what TC is and what CF is.

2020-12-20 04:38 UTC, ankingcodes commented on codemon/CodemonHelp.py
> +  print("codemon init <contestName> - - - - - - - Initialises a contest")
Please don't alter previously added help messages, revert them to original.

2020-12-20 04:38 UTC, ankingcodes commented on codemon/CodemonHelp.py
> +  print("codemon listen - - - - - - - - - - - - - Listens for changes in code. Also, compiles and gives output")
Revert back to previous version

2020-12-20 04:40 UTC, ankingcodes commented
@lucifer0987 - You didn't have to make changes to all help messages, most of them were concise already. Read the issue properly, clearly, the help messages of codemon fetch were improper.

2020-12-20 08:46 UTC, lucifer0987 commented
@ankingcodes 
made changes as you requested. Please review.

2020-12-21 09:28 UTC, ankingcodes commented
Closing this since it was already fixed by #72

2020-12-21 09:28 UTC, closed without merging